### PR TITLE
Prevent yesqa from removing necessary qa's

### PR DESCRIPTION
**Pull request by msmdev**
...  by pinning flake8 to v3.8.4 in additional_dependencies of yesqa in .pre-commit-config.yaml.

### CODE REVIEW

**Comment by msmdev** [comment]
@michalk8, we had already several version-interplay-issues during linting that had to be solved by pinning in recent time. Maybe, we should update .pre-commit-config.yaml? I tried to do so via `pre-commit autoupdate` but ran into incompatibility issues between yesqa and flake8 and some problems with rstcheck.

**Comment by michalk8** [comment]
> @michalk8, we had already several version-interplay-issues during linting that had to be solved by pinning in recent time. Maybe, we should update .pre-commit-config.yaml? I tried to do so via pre-commit autoupdate but ran into incompatibility issues between yesqa and flake8 and some problems with rstcheck.

I updated the `pre-commits` and removed 1 redundant one + `flake8-mock` causing issue with `yesqa`. Could you please try locally if this works for you?

**Comment by msmdev** [comment]
> > @michalk8, we had already several version-interplay-issues during linting that had to be solved by pinning in recent time. Maybe, we should update .pre-commit-config.yaml? I tried to do so via pre-commit autoupdate but ran into incompatibility issues between yesqa and flake8 and some problems with rstcheck.
> 
> I updated the `pre-commits` and removed 1 redundant one + `flake8-mock` causing issue with `yesqa`. Could you please try locally if this works for you?

Nice! This solved the issue.
Works fine locally, but can't we remove `additional_dependencies: [numpy==1.20.0, scipy>=1.6.0]` from `mypy` and `additional_dependencies: [click==8.0.1, toml]` from `black`? Locally, it works without those pins.

**Comment by michalk8** [comment]
If we remove `numpy/scipy` from `mypy`, it will not check for these errors afaik. `click` can be removed, `toml` is needed since we configure `black` in `pyproject.toml`.

**Comment by msmdev** [comment]
> If we remove `numpy/scipy` from `mypy`, it will not check for these errors afaik. `click` can be removed, `toml` is needed since we configure `black` in `pyproject.toml`.

Sorry, my bad... I overlooked toml...
Fixed it and reintroduced `scipy` and `numpy` for `mypy`.
Anyway, removing `additional_dependencies: [black==20.8b1]` from `blacken-docs` should be fine?

**Comment by michalk8** [comment]
I'd just update it, see here as to why: https://github.com/asottile/blacken-docs#usage-with-pre-commit

**Comment by msmdev** [comment]
> I'd just update it, see here as to why: https://github.com/asottile/blacken-docs#usage-with-pre-commit

Done (a little messy, since I had to amend a typo in my commit message...). -.-

**Review by michalk8 — APPROVED** [review]

**Comment by msmdev** [comment]
@michalk8, suddenly no-commit-to-branch is failing. Mb. related to your last [change](https://github.com/msmdev/pyGPCCA/pull/40/commits/3d4babb1ff8bf5925f83ae72283c2de8ff9c8da4)

**Comment by michalk8** [comment]
> @michalk8, suddenly no-commit-to-branch is failing. Mb. related to your last [change](https://github.com/msmdev/pyGPCCA/pull/40/commits/3d4babb1ff8bf5925f83ae72283c2de8ff9c8da4)?

Weird, since you merged after I committed and it shouldn't be related to the contents of that commit... I'd personally remove that check anyways.

**Comment by msmdev** [comment]
> > @michalk8, suddenly no-commit-to-branch is failing. Mb. related to your last [change](https://github.com/msmdev/pyGPCCA/pull/40/commits/3d4babb1ff8bf5925f83ae72283c2de8ff9c8da4)?
> 
> Weird, since you merged after I committed and it shouldn't be related to the contents of that commit... I'd personally remove that check anyways.

I guess, I solved the issue in #41.

**Pull request merged**
