### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by michalk8**
I've added the installation instructions for Debian-based system and macOS (not sure about this one), there are still some TODOs.
Perhaps @Marius1311 you could handle it?
I've also included links to conda, though this can be done once it's on the PyPI.

closes #6

### CODE REVIEW

**Comment by michalk8** [comment]
After the README has been finalized, I will check the badge links + typos.
ping @msmdev - if you want to add some other custom badge (e.g. link to the paper, you can create one using [https://shields.io/](https://shields.io/) - and link the target in the README, as it's done with other badges)

**Comment by msmdev** [comment]
hmm, not sure, if my paper badge is really nice...

**Comment by msmdev** [comment]
What about [conf.py](https://github.com/msmdev/pyGPCCA/blob/update-readme/docs/source/conf.py), [index.py],(https://github.com/msmdev/pyGPCCA/blob/update-readme/docs/source/index.rst) [installation.py](https://github.com/msmdev/pyGPCCA/blob/update-readme/docs/source/installation.rst)?

**Comment by michalk8** [comment]
ping @msmdev @Marius1311 
Both of you, please don't forget to run `pre-commit install` from the root of the repo, otherwise the linting doesn't pass.

@msmdev 
re badge: how about Zenodo-style? like here: https://github.com/sympy/sympy

**Comment by msmdev** [comment]
> pre-commit install

@michalk8 could you please elaborate this a little more detailed?
Do I need to first ``pip install pre-commit`` or just ``pre-commit install`` in the repo root?
Do you mean ``pip install -e '.[dev]' git+https://github.com/msmdev/pygpcca``?

**Comment by msmdev** [comment]
> @michalk8 could you please elaborate this a little more detailed?
> Do I need to first `pip install pre-commit` or just `pre-commit install` in the repo root?
> I guess there is a typo and it should read `pip install -e '.[dev]'`?
> In what order should it be done?

Ok, I guess I did it by
1. ``pip install pre-commit``
2. ``pre-commit install``
3. ``pip install -e '.[dev]'``

Alright?

**Comment by michalk8** [comment]
>  I guess there is a typo and it should read pip install -e '.[dev]'?

You're right, sorry.

The `pip install -e '.[dev]'` installs the dev. dependencies (which is just `pre-commit` and `bump2version`).
After `pre-commit` is pip-installed, you need to initialized it in the repo by running `pre-commit install` from the repo's root.
This will run series of checks before committing and disallow you to commit the files unless all of them are ok (you can disable it by running `git commit --no-verify`, but it's discouraged).

If you want to run tests, we use [tox](https://tox.readthedocs.io/en/latest/) to create the environments (also for linting). Then you can run: `tox -e py38-linux` to test (if you're on Linux and have Python3.8 intalled). `tox -e lint` just run `pre-commit`.
`tox -e docs` builds the documentation under `docs`.

**Comment by michalk8** [comment]
> What about [conf.py](https://github.com/msmdev/pyGPCCA/blob/update-readme/docs/source/conf.py), [index.py](https://github.com/msmdev/pyGPCCA/blob/update-readme/docs/source/index.rst), [installation.py](https://github.com/msmdev/pyGPCCA/blob/update-readme/docs/source/installation.rst)?

These are currently not used (they were intended to be build by sphinx and put on e.g. readthedocs.io).

**Comment by michalk8** [comment]
@msmdev @Marius1311 
From my point, this can be merged (unless we want to add the title figure). Afterwards, 3 things remain:
- check for typos in the README/docs (MK)
- check whether links point to (or will point to) correct things (MK)
- add PYPI_PASSWORD secret to this repo's secrets, if not already done (BR)
- maybe update keywords for PyPI [here](https://github.com/msmdev/pyGPCCA/blob/main/setup.py#L67) (BR)
- \*resolve: https://github.com/msmdev/pyGPCCA/pull/6#issuecomment-763725426 (BR,ML,MK)

\*Currently, there are 2 functions (`gpcca_coarsegrain`, `stationary_distribution` and `GPCCA` class). Doing this would lighten the README (we could keep inside only simple installation instructions and delegate troubleshooting/usage/API to the docs).

**Comment by Marius1311** [comment]
> ping @msmdev @Marius1311
> Both of you, please don't forget to run `pre-commit install` from the root of the repo, otherwise the linting doesn't pass (you need `pip install -e.'[dev]'`)
> 
> @msmdev
> re badge: how about Zenodo-style? like here: https://github.com/sympy/sympy

sorry @michalk8, forgot about that but did it now.

**Comment by Marius1311** [comment]
> @msmdev @Marius1311
> From my point, this can be merged (unless we want to add the title figure). Afterwards, 3 things remain:
> 
> * check for typos in the README/docs (MK)
> * check whether links point to (or will point to) correct things (MK)
> * add PYPI_PASSWORD secret to this repo's secrets, if not already done (BR)
> * maybe update keywords for PyPI [here](https://github.com/msmdev/pyGPCCA/blob/main/setup.py#L67) (BR)
> * *resolve: [#6 (comment)](https://github.com/msmdev/pyGPCCA/pull/6#issuecomment-763725426) (BR,ML,MK)
> 
> *Currently, there are 2 functions (`gpcca_coarsegrain`, `stationary_distribution` and `GPCCA` class). Doing this would lighten the README (we could keep inside only simple installation instructions and delegate troubleshooting/usage/API to the docs).

I don't get it, sorry. What do you refer to by saying "doing this"? You mean building an API with sphinx?

**Comment by michalk8** [comment]
> I don't get it, sorry. What do you refer to by saying "doing this"? You mean building an API with sphinx?

By building docs on `readthedocs.io`.

**Comment by msmdev** [comment]
I think building docs on readthedocs.io is a good idea.

**Comment by msmdev** [comment]
I will have lunch break and afterwards add the PyPI secret and check the keywords :)

**Comment by michalk8** [comment]
> I think building docs on readthedocs.io is a good idea.

Ok, then I will create a sep. issue for readthedocs.io. Maybe one of you @msmdev @Marius1311 could create one small `.ipynb` file demonstrating the usage - I could then add it to the readthedocs page.

**Comment by msmdev** [comment]
@michalk8 after adding keywords in setup.py and trying to commit the change locally linting fails with two errors not related to setup.py:
"""
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

pygpcca/_gpcca.py:36:5: error: Module 'functools' has no attribute 'cached_property'  [attr-defined]
Found 1 error in 1 file (checked 1 source file)

"""

**Comment by msmdev** [comment]
PYPI_PASSWORD was added to secrets.

**Comment by michalk8** [comment]
> @michalk8 after adding keywords in setup.py and trying to commit the change locally linting fails with two errors not related to setup.py:

Not sure what Python version you're using, but when running `pre-commit run --all-files` on 3.8, it's fine. You can just add:
```
# type: ignore[attr-defined]
```
on the same line as the error occurs (think cached_propery is >=3.8, so for 3.7 we have the ImportError).

**Comment by msmdev** [comment]
@michalk8 done as you said and added the comment on line 36 og _gppca.py.
setup.py is commited now, but _gpcca fails with:
```
mypy.....................................................................Passed
black....................................................................Failed
- hook id: black
- files were modified by this hook

reformatted /home/breuter/g-pcca/pyGPCCA/pygpcca/_gpcca.py
All done! ✨ 🍰 ✨
1 file reformatted, 1 file left unchanged.

isort....................................................................Passed
Strip unnecessary `# noqa`s..............................................Passed
Pretty format YAML...................................(no files to check)Skipped
Detect Private Key.......................................................Passed
Don't commit to branch...................................................Passed
Check for merge conflicts................................................Passed
Check python ast.........................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Check for added large files..............................................Passed
Check that executables have shebangs.................(no files to check)Skipped
Fix python encoding pragma...............................................Passed
Fix End of Files.........................................................Passed
Mixed line ending........................................................Passed
Trim Trailing Whitespace.................................................Passed
Tests should end in _test.py.........................(no files to check)Skipped
Check for case conflicts.................................................Passed
Check docstring is first.................................................Passed
Check Yaml...........................................(no files to check)Skipped
Check Toml...........................................(no files to check)Skipped
Fix requirements.txt.................................(no files to check)Skipped
flake8...................................................................Passed
autoflake................................................................Passed
Check executable files use .sh extension.............(no files to check)Skipped
Test shell scripts with shellcheck...................(no files to check)Skipped
rstcheck.............................................(no files to check)Skipped
blacken-docs.............................................................Passed
pyupgrade................................................................Passed
check for eval().........................................................Passed
type annotations not comments............................................Passed
check blanket noqa.......................................................Passed
rst ``code`` is two backticks........................(no files to check)Skipped
rst directives end with two colons.......................................Passed
rst ``inline code`` next to normal text..............(no files to check)Skipped
doc8.................................................(no files to check)Skipped

```

**Comment by msmdev** [comment]
Python version is 3.7.4.

**Comment by michalk8** [comment]
> @michalk8 done as you said and added the comment on line 36 og _gppca.py.
setup.py is commited now, but _gpcca fails with:

Not it looks good, just need to add the files `black` formatted and commit again (try git status and you should see the files has changed). I usually have an `alias gac='git add --all && git commit'` and run `gac` twice.

**Comment by michalk8** [comment]
> Python version is 3.7.4.

Great, after #6, we can merge this. Please also don't forget to add some metadata (esp. the newly-added keywords from #6) on the RTD, as well as project url (this repo).

**Comment by michalk8** [comment]
> https://github.com/msmdev/pyGPCCA/pull/6/commits/4c3a313cb81f9e3c71f4ad7f642e867375860782

Linting in this commit failed becaue I've configure mypy to warn about unused ignores, so I've reverted that - it should be fine now.

**Pull request merged**
