### PR TITLE
Rtd

### LINKED ISSUE #8: Readthedocs
Push the documentation to readthedocs.yml. TODOs:
- [x] create .readthedocs.yml
- [ ] update .css file (for now, just increase the width/change style)
- [x] move intallation troubleshooting from README
- [ ] update badges, check links
- [ ] add a small usage notebook - I think this should this replace the usage @msmdev (i.e. just move the explanations into the notebook)
- [ ] add binder links, related to above (I will need a requirements file which can run the notebook - will most likely need numpy/scipy/matplotlib only)

### PR DESCRIPTION
**Pull request by michalk8**
closes #8 

> OK, will create a small notebook with some example matrix from the tests.
@michalk8 were (folder) should the .ipynb be placed?

@msmdev place it under `docs/source/example.ipynb` (feel free to rename the file name).

### CODE REVIEW

**Comment by michalk8** [comment]
@msmdev you will have to create RTD account if you don't have one yet and - I don't have the permission.

**Comment by msmdev** [comment]
> @msmdev you will have to create RTD account if you don't have one yet and - I don't have the permission.

RTD account was created and linked with my Github.

**Comment by michalk8** [comment]
> RTD account was created and linked with my Github.

Great, can you import the pyGPCCA project? Afterwards, we can merge #6 with the new keywords, then this. Then the docs should be built (currently, `.readthedocs.yml` is only on this `branch`, needs to be on `main`).

**Comment by msmdev** [comment]
Imported pyGPCCA in RTD!

**Comment by msmdev** [comment]
Guess [this](https://github.com/msmdev/pyGPCCA/pull/6#issuecomment-764699584) belongs here? :)

**Comment by msmdev** [comment]
How/were exactly should I add the metadata on the RTD, as well as project url (this repo)?
Sorry, I'm kind of a dummy sometimes... XD

**Comment by msmdev** [comment]
> How/were exactly should I add the metadata on the RTD, as well as project url (this repo)?
> Sorry, I'm kind of a dummy sometimes... XD

Found it in the "Administration" setting of pyGPCCA on readthedocs.org :)

**Comment by msmdev** [comment]
Seems to build and can be found on [RTD](https://pygpcca.readthedocs.io/en/latest/?)
Anything missing? API token from readthedocs.org in the repo secrets isn't needed?

**Comment by michalk8** [comment]
> Seems to build and can be found on RTD
Anything missing? API token from readthedocs.org in the repo secrets isn't needed?

This seems to be a stale one (from current main), I can see old installation instructions).

> API token from readthedocs.org in the repo secrets isn't needed?

No, everything shoul be fine. 

I will fix the conflict + merge, then in a hopefully penultimate PR, you can add the example and I will check the links.
If you have any theme preference (we now use the sphinx' default, here's an inspiration: https://sphinxthemes.com/)

**Comment by msmdev** [comment]
Ok, I am preparing the notebook.
Please don't close PR [#7](https://github.com/msmdev/pyGPCCA/pull/7) yet - I am still waiting for confirmation there...

**Pull request merged**
