### PR TITLE
Patch release preparation

### PR DESCRIPTION
**Pull request by michalk8**
Bump ``numpy>=1.17`` (previous versions are ending support in a few days) + I also hope to vacate the CI cache to see why it's failing.

### CODE REVIEW

**Comment by michalk8** [comment]
I've disabled PETSc/SLEPc testing, since there are some problems with `mpif90`, I will fix reintroduce them later in a separate PR.
@msmdev @Marius1311 after this is merged, I can make the new patch release (for the adjusted thresholds).

**Comment by msmdev** [comment]
Thank you @michalk8 for taking care of this!
Guess, I can simply merge the conda-forge [PR](https://github.com/conda-forge/pygpcca-feedstock/pull/8)?

**Comment by michalk8** [comment]
>  Guess, I can simply merge the conda-forge PR?

Yes, this can be merged, thanks!

**Comment by msmdev** [comment]
Done!

**Comment by Marius1311** [comment]
Thanks @michalk8 and @msmdev!

**Pull request merged**
