### PR TITLE
Adjust chi threshold

### LINKED ISSUE #33: Adjust threshold for negative elements in `chi`
See this issue in CellRank: https://github.com/theislab/cellrank/issues/781

### PR DESCRIPTION
**Pull request by michalk8**
closes #33 
would mb wait for a reply in https://github.com/theislab/cellrank/issues/781 whether this solves it

### CODE REVIEW

**Comment by Marius1311** [comment]
It seems that this solved the linked issue!

**Comment by Marius1311** [comment]
Thus, I think we can merge this

**Comment by msmdev** [comment]
I assume we could be even less strict with the threshold: after this change the threshold will be `-1e3 * EPS` which is around `-2.22e-13` using `np.float64`. I think setting it to `-2.22e-12` would still be totally sane.

**Comment by Marius1311** [comment]
yes please! Thanks @msmdev

**Pull request merged**
