### PR TITLE
Print some deviations

### LINKED ISSUE #28: Print deviations from thresholds
Often, I get a warning or an error because some threshold failed, but it's always really hard to figure out how far I'm off. I'm adding print statements for these deviations.

### PR DESCRIPTION
**Pull request by Marius1311**
Add print statements for threshold deviations.

closes #28, related to #27 and #19

### CODE REVIEW

**Comment by Marius1311** [comment]
Hi @michalk8, could you add a few tests for this please? Also, @msmdev, this is a really minor PR, just adds some more print outs when some of the thresholds fails to ease debugging/potentially changing some thresholds.

**Comment by michalk8** [comment]
@Marius1311 I don't think it's necessary - we already have pattern matching on errors.

**Comment by Marius1311** [comment]
Can you explain what that means please?

**Comment by michalk8** [comment]
> Can you explain what that means please?

See e.g. here: https://github.com/msmdev/pyGPCCA/blob/main/tests/test_gpcca.py#L283

**Comment by Marius1311** [comment]
I'm still not quite sure how that's relevant to the problem I'm describing. I often get errors from pyGPCCA because some threshold fails, and I would like to know by _how much_ I'm failing, so I can figure out whether this may just be numerical or systematic, and whether we may have to adjust a threshold.

**Comment by msmdev** [comment]
> Hi @michalk8, could you add a few tests for this please? Also, @msmdev, this is a really minor PR, just adds some more print outs when some of the thresholds fails to ease debugging/potentially changing some thresholds.

I think it would indeed be good to print the actual deviations out in case of failing threshold checks.
Anyway, I guess we have to reevaluate all threshold values and increase them were possible or even replace some of the errors with warnings, if justified.

**Comment by Marius1311** [comment]
@michalk8, your input would be appreciated

**Pull request merged**
