### PR TITLE
Silent B028 from flake8-bugbear

### PR DESCRIPTION
**Pull request by msmdev**

### CODE REVIEW

**Comment by msmdev** [comment]
Also pre-commit run --all-files graciously passes both here and in `main`, but linting is failing in CI.

**Comment by msmdev** [comment]
> I'd suggest removing this line: https://github.com/msmdev/pyGPCCA/blob/main/.github/workflows/ci.yml#L32

What is the effect of this line, exactly?

**Comment by michalk8** [comment]
> What is the effect of this line, exactly?

It's an alternative key, when it cannot be found [here](https://github.com/msmdev/pyGPCCA/blob/main/.github/workflows/ci.yml#L30).

**Comment by michalk8** [comment]
> > > What is the effect of this line, exactly?
> > 
> > 
> > It's an alternative key, when it cannot be found [here](https://github.com/msmdev/pyGPCCA/blob/main/.github/workflows/ci.yml#L30).
> 
> So it's basically using a old cached version of the pre-commit-config.yaml?

Yes, it shouldn't be there. But looking closely at the [run](https://github.com/msmdev/pyGPCCA/actions/runs/4234713944/jobs/7357395898#step:4:17), no cache-hit happened, so it's something else.

However, I think the `B028` should be fixed in the code; tried locally (with different Python versions), can't also seem to reproduce the error on CI.

**Comment by msmdev** [comment]
> > > > What is the effect of this line, exactly?
> > > 
> > > 
> > > It's an alternative key, when it cannot be found [here](https://github.com/msmdev/pyGPCCA/blob/main/.github/workflows/ci.yml#L30).
> > 
> > 
> > So it's basically using a old cached version of the pre-commit-config.yaml?
> 
> Yes, it shouldn't be there. But looking closely at the [run](https://github.com/msmdev/pyGPCCA/actions/runs/4234713944/jobs/7357395898#step:4:17), no cache-hit happened, so it's something else.
> 
> However, I think the `B028` should be fixed in the code; tried locally (with different Python versions), can't also seem to reproduce the error on CI.
> 
> UPDATE: Can reproduce after I remove `~/.cache/pre-commit`.

What do you mean by "the `B028` should be fixed in the code"?
If I add `# noqa B028` in the respective lines, they are removed by yesqa during linting... so I can't prevent flake8 from complaining.

**Comment by msmdev** [comment]
Anyhow, flake8 is only complaining during the GitHub workflow - locally flake8 is graciously passing without `# noqa B028`...

**Comment by msmdev** [comment]
@michalk8, ooook, ignoring B028 in tox.ini solved the problem, but I'm still quite upset why flake8 is issuing B028 during GitHub workflows and not locally. -.-

**Comment by msmdev** [comment]
> @michalk8, ooook, ignoring B028 in tox.ini solved the problem, but I'm still quite upset why flake8 is issuing B028 during GitHub workflows and not locally. -.-

@michalk8, would you please review? Thank you!

**Review by michalk8 — APPROVED** [review]
LGTM, thanks @msmdev !

**Pull request merged**
