### PR TITLE
Add application example to example.ipynb

### PR DESCRIPTION
**Pull request by msmdev**
I added an application example in the example notebook opening a new branch, since I wasn't sure, if we really want to employ PR [#11](https://github.com/msmdev/pyGPCCA/pull/11).

### CODE REVIEW

**Comment by michalk8** [comment]
> I added an application example in the example notebook opening a new branch, since I wasn't sure, if we really want to employ PR #11.

Great, thanks a lot @msmdev! I will take a look and see how to add the binder link.

**Comment by msmdev** [comment]
@michalk8 could you mb. take a short look on the notebook, e.g. if the format is fine?
Also: There was a warning when using GPCCA.minchi():
```
/home/breuter/g-pcca/pyGPCCA/pygpcca/_gpcca.py:230: UserWarning: The Schur vectors aren't D-orthogonal so they are D-orthogonalized.
  warnings.warn("The Schur vectors aren't D-orthogonal so they are D-orthogonalized.")
```
It's not critical, but a little unexpected - did you get this warning often?

**Comment by michalk8** [comment]
> It's not critical, but a little unexpected - did you get this warning often?

In CellRank's examples/other stuff, not really, but during testing I remember these esp. for example matrix mu=0.

Wha'ts problematic is that I can't run this on my machine:
```pytb
LinAlgError                               Traceback (most recent call last)
<ipython-input-4-ad7dd23284f2> in <module>
----> 1 gpcca.minChi(2, 8)

~/.miniconda3/envs/squidpy/lib/python3.7/site-packages/pygpcca/_gpcca.py in minChi(self, m_min, m_max)
    845 
    846         # Calculate Schur matrix R and Schur vector matrix X, if not adequately given.
--> 847         self._do_schur_helper(m_max)
    848         if TYPE_CHECKING:
    849             assert isinstance(self._p_X, np.ndarray)

~/.miniconda3/envs/squidpy/lib/python3.7/site-packages/pygpcca/_gpcca.py in _do_schur_helper(self, m)
    811         else:
    812             self._p_X, self._p_R, self._p_eigenvalues = _do_schur(
--> 813                 self._P, eta=self._eta, m=m, z=self._z, method=self._method
    814             )
    815 

~/.miniconda3/envs/squidpy/lib/python3.7/site-packages/pygpcca/_gpcca.py in _do_schur(P, eta, m, z, method, tol_krylov)
    223 
    224     # Make a Schur decomposition of P_bar and sort the Schur vectors (and form).
--> 225     R, Q, eigenvalues = sorted_schur(P_bar, m, z, method, tol_krylov=tol_krylov)  # Pbar!!!
    226 
    227     # Orthonormalize the sorted Schur vectors Q via modified Gram-Schmidt-orthonormalization,

~/.miniconda3/envs/squidpy/lib/python3.7/site-packages/pygpcca/_sorted_schur.py in sorted_schur(P, m, z, method, tol_krylov)
    368     # compute the sorted schur decomposition
    369     if method == "brandts":
--> 370         R, Q, eigenvalues = sorted_brandts_schur(P=P, k=m, z=z)
    371     elif method == "krylov":
    372         R, Q, eigenvalues, _ = sorted_krylov_schur(P=P, k=m, z=z, tol=tol_krylov)

~/.miniconda3/envs/squidpy/lib/python3.7/site-packages/pygpcca/_sorted_schur.py in sorted_brandts_schur(P, k, z)
    314 
    315     # Sort the Schur matrix and vectors.
--> 316     Q, R, ap = sort_real_schur(Q, R, z=z, b=k)
    317 
    318     # Warnings

~/.miniconda3/envs/squidpy/lib/python3.7/site-packages/pygpcca/_sort_real_schur.py in sort_real_schur(Q, R, z, b, inplace)
    133         vw = v + w
    134         nrA = np.linalg.norm(R[vw, :][:, vw], ord=np.inf)  # compute norm of the matrix A from eq. (6)
--> 135         Q, R = swap(Q, R, v, w, inplace=True)  # swap the blocks
    136         p[k], p[k + 1] = p[k + 1], p[k]  # debug
    137         s[k + 1] = s[k] + s[k + 2] - s[k + 1]  # update positions of blocks

~/.miniconda3/envs/squidpy/lib/python3.7/site-packages/pygpcca/_sort_real_schur.py in swap(U, S, v, w, inplace)
    447         sigp[[k, P[k]]] = sigp[[P[k], k]].copy()
    448     r = e * r[sigp]  # ... scale and permute the right-hand side.
--> 449     x = np.linalg.solve(H, np.linalg.solve(L, r))  # and solve the two triangular systems.
    450     sigq = np.arange(p * q)
    451     for k in range(p * q - 1):  # Implement permutation Q of the LU-decomposition PAQ=LU ...

<__array_function__ internals> in solve(*args, **kwargs)

~/.miniconda3/envs/squidpy/lib/python3.7/site-packages/numpy/linalg/linalg.py in solve(a, b)
    392     signature = 'DD->D' if isComplexType(t) else 'dd->d'
    393     extobj = get_linalg_error_extobj(_raise_linalgerror_singular)
--> 394     r = gufunc(a, b, signature=signature, extobj=extobj)
    395 
    396     return wrap(r.astype(result_t, copy=False))

~/.miniconda3/envs/squidpy/lib/python3.7/site-packages/numpy/linalg/linalg.py in _raise_linalgerror_singular(err, flag)
     86 
     87 def _raise_linalgerror_singular(err, flag):
---> 88     raise LinAlgError("Singular matrix")
     89 
     90 def _raise_linalgerror_nonposdef(err, flag):

LinAlgError: Singular matrix
```
On Python3.8 and Python3.7. However, in the same envs. the tests pass. This happens in the same place as on macOS failing CI we've discussed previously.

**Comment by michalk8** [comment]
Here's the sequence of systems it's trying to solve, failing on the last one:
```python
# H L r
[[-0.00270954]] [[1.]] [-4.51742398e-19]
[[-0.00776541]] [[1.]] [-7.35688367e-08]
[[-0.00505586]] [[1.]] [-4.13972722e-19]
[[-0.00603464]] [[1.]] [4.31622769e-19]
[[-0.01649712]] [[1.]] [-7.47396998e-07]
[[-8.8817842e-16]] [[1.]] [9.86076132e-32]
[[-0.00417751]] [[1.]] [-5.81921835e-20]
[[-0.01463998]] [[1.]] [1.89901267e-18]
[[0.]] [[1.]] [-0.]
```

**Comment by Marius1311** [comment]
> @michalk8 could you mb. take a short look on the notebook, e.g. if the format is fine?
> Also: There was a warning when using GPCCA.minchi():
> 
> ```
> /home/breuter/g-pcca/pyGPCCA/pygpcca/_gpcca.py:230: UserWarning: The Schur vectors aren't D-orthogonal so they are D-orthogonalized.
>   warnings.warn("The Schur vectors aren't D-orthogonal so they are D-orthogonalized.")
> ```
> 
> It's not critical, but a little unexpected - did you get this warning often?

I get this whenever I apply GPCCA to reducible matrices - other than that, I haven't encountered this warning.

**Comment by msmdev** [comment]
> > @michalk8 could you mb. take a short look on the notebook, e.g. if the format is fine?
> > Also: There was a warning when using GPCCA.minchi():
> > ```
> > /home/breuter/g-pcca/pyGPCCA/pygpcca/_gpcca.py:230: UserWarning: The Schur vectors aren't D-orthogonal so they are D-orthogonalized.
> >   warnings.warn("The Schur vectors aren't D-orthogonal so they are D-orthogonalized.")
> > ```
> > 
> > 
> > It's not critical, but a little unexpected - did you get this warning often?
> 
> I get this whenever I apply GPCCA to reducible matrices - other than that, I haven't encountered this warning.

@Marius1311 interesting - @michalk8 did you experience the same?

**Comment by msmdev** [comment]
Obviously, there is a problem with macOS in the sense that the implementation of certain linear algebra routines seems to be a little unstable...
The occurence of this warning just informs us that sort_real_schur didn't produce D-orthogonal Schur vectors - which in my experience mostly happens due to imprecision or numerical instability when doing all the swaps in sort_real_schur.

I would assume that this warning only appears, if ``method='brandts'``?

**Comment by msmdev** [comment]
I would upvote for replacing mu=0 in the in the example with mb. mu=100 - did you have any problems there?

Regarding the tests, we could skip the tests for mu=0 for the time being on macOS, if we aren't already doing this. 

Regarding the warning: it might be confusing for users without any real benefit, so we could add a developer mode of verbosity and only issue this warning, if one explicitly chooses developer verbosity (and mb. some others as well?)
@Marius1311 @michalk8 what is your oppinion here?

**Comment by michalk8** [comment]
> I would upvote for replacing mu=0 in the in the example with mb. mu=100 - did you have any problems there?

No, mu=100 is fine for me.

> Regarding the tests, we could skip the tests for mu=0 for the time being on macOS, if we aren't already doing this.

Yes, we're already doing this, but only using `method='brantds'`, for `'krylov'`, this seems to be fine.

> Regarding the warning: it might be confusing for users without any real benefit, so we could add a developer mode of verbosity and only issue this warning, if one explicitly chooses developer verbosity (and mb. some others as well?)
@Marius1311 @michalk8 what is your oppinion here?

Had a chat with Marius, we both agree - I've set the verbosity to `DEBUG`.

**Comment by msmdev** [comment]
@michalk8 thx for taking care.
Anyway: there are relatively large negative elements in the resulting coarse transition matrix for mu=0. Mb. this is not optimal for an example - anyone @michalk8 @Marius1311  having a better toy matrix not resulting in significant negative elements in the coarse matrix?

**Comment by msmdev** [comment]
@michalk8 something else regarding RTD: [this](https://pygpcca.readthedocs.io/en/latest/api/pygpcca.stationary_distribution.html) API page looks weird - any idea why?

**Comment by michalk8** [comment]
> @michalk8 something else regarding RTD: this API page looks weird - any idea why?

Yes, it's because of `@singledispatch` decorator, used to distinguis between sparse and dense, see related Sphinx issue:
https://github.com/sphinx-doc/sphinx/issues/2815

Btw, I've updated  the style - what's your opinion? You can create the docs as `tox -e docs`, on the bottom, it will print out where you can find `index.html` - just open it with your browser.

**Comment by michalk8** [comment]
> Anyway: there are relatively large negative elements in the resulting coarse transition matrix for mu=0. Mb. this is not optimal for an example - anyone @michalk8 @Marius1311 having a better toy matrix not resulting in significant negative elements in the coarse matrix?

There are some matrices in `tests/conftest.py` - https://github.com/msmdev/pyGPCCA/blob/main/tests/conftest.py#L2851
we could use - I haven't really checked them really w.r.t. to negative elems in coarse-grained TM.

**Comment by msmdev** [comment]
> > @michalk8 something else regarding RTD: this API page looks weird - any idea why?
> 
> Yes, it's because of `@singledispatch` decorator, used to distinguis between sparse and dense, see related Sphinx issue:
> [sphinx-doc/sphinx#2815](https://github.com/sphinx-doc/sphinx/issues/2815)
> 
> Btw, I've updated the style - what's your opinion? You can create the docs as `tox -e docs`, on the bottom, it will print out where you can find `index.html` - just open it with your browser.

Hmm... when doing so this happens:
```
docs create: /home/breuter/g-pcca/pyGPCCA/.tox/docs
SKIPPED: InterpreterNotFound: python3.8
___________________________________ summary ____________________________________
SKIPPED:  docs: InterpreterNotFound: python3.8
  congratulations :)
```

**Comment by msmdev** [comment]
> > Anyway: there are relatively large negative elements in the resulting coarse transition matrix for mu=0. Mb. this is not optimal for an example - anyone @michalk8 @Marius1311 having a better toy matrix not resulting in significant negative elements in the coarse matrix?
> 
> There are some matrices in `tests/conftest.py` - https://github.com/msmdev/pyGPCCA/blob/main/tests/conftest.py#L2851
> we could use - I haven't really checked them really w.r.t. to negative elems in coarse-grained TM.

Okay, I will play around with them a little :)

**Comment by michalk8** [comment]
> Remember: I'm on 3.7.4

Just change the lhis line to `basepython = python3.7`, should be fine: https://github.com/msmdev/pyGPCCA/blob/main/tox.ini#L165

**Comment by msmdev** [comment]
> > Remember: I'm on 3.7.4
> 
> Just change the lhis line to `basepython = python3.7`, should be fine: https://github.com/msmdev/pyGPCCA/blob/main/tox.ini#L165

Yes that worked... you adjusted the blue color, right? Looks nice :)

**Comment by msmdev** [comment]
I added an extra copyright note to the function docstrings in _utils.py - just in case.
@michalk8 the functions _sds and _sdd don't have docstrings currently - do they also origin from msmtools?

**Comment by Marius1311** [comment]
> @michalk8 thx for taking care.
> Anyway: there are relatively large negative elements in the resulting coarse transition matrix for mu=0. Mb. this is not optimal for an example - anyone @michalk8 @Marius1311 having a better toy matrix not resulting in significant negative elements in the coarse matrix?

Yes, we could use the matrix from Supplemental. Fig. 1 in the manuscript - @msmdev, you find the matrix, and the whole analysis done to it in that figure, publicly available here: https://github.com/theislab/cellrank_reproducibility/blob/main/notebooks/suppl_fig_GPCCA/ML-2020-10-17_GPCCA_toy_example.ipynb

**Comment by Marius1311** [comment]
That notebook also has the nice plotting of the graph, which makes the whole thing very visual and easy to follow for a newcomer.

**Comment by Marius1311** [comment]
Regarding the D-orthogonality warning: at least for reducible matrices, the computation of the stationary distribution will fail. In such a case, it would be good to tell the user that the matrix is reducible and that the stationary dist. is not unique.

**Comment by msmdev** [comment]
> Regarding the D-orthogonality warning: at least for reducible matrices, the computation of the stationary distribution will fail. In such a case, it would be good to tell the user that the matrix is reducible and that the stationary dist. is not unique.

Sure, we better should issue that warning in the resp. function, i.e. stationary_distribution.

**Comment by msmdev** [comment]
> > @michalk8 thx for taking care.
> > Anyway: there are relatively large negative elements in the resulting coarse transition matrix for mu=0. Mb. this is not optimal for an example - anyone @michalk8 @Marius1311 having a better toy matrix not resulting in significant negative elements in the coarse matrix?
> 
> Yes, we could use the matrix from Supplemental. Fig. 1 in the manuscript - @msmdev, you find the matrix, and the whole analysis done to it in that figure, publicly available here: https://github.com/theislab/cellrank_reproducibility/blob/main/notebooks/suppl_fig_GPCCA/ML-2020-10-17_GPCCA_toy_example.ipynb

Ok, thx @Marius1311, I'm taking a look :)

**Comment by msmdev** [comment]
> > > @michalk8 thx for taking care.
> > > Anyway: there are relatively large negative elements in the resulting coarse transition matrix for mu=0. Mb. this is not optimal for an example - anyone @michalk8 @Marius1311 having a better toy matrix not resulting in significant negative elements in the coarse matrix?
> > 
> > 
> > Yes, we could use the matrix from Supplemental. Fig. 1 in the manuscript - @msmdev, you find the matrix, and the whole analysis done to it in that figure, publicly available here: https://github.com/theislab/cellrank_reproducibility/blob/main/notebooks/suppl_fig_GPCCA/ML-2020-10-17_GPCCA_toy_example.ipynb
> 
> Ok, thx @Marius1311, I'm taking a look :)

When doing pygpcca.GPCCA(P).minChi(2,11) for your matrix, I get a warning
```
/home/breuter/g-pcca/pyGPCCA/pygpcca/_sort_real_schur.py:106: ComplexWarning: Casting complex values to real discards the imaginary part
  p[k] = R[sk, sk] + np.lib.scimath.sqrt(R[sk + 1, sk] * R[sk, sk + 1])  # store the eigenvalues
```
@Marius1311 did you also experience this?

**Comment by msmdev** [comment]
Another suboptimal behaviour:
If I do `pygpcca.GPCCA(P).minChi(2,11)` it gives me all minChi values (and the aforementioned warning), but if I do `pygpcca.GPCCA(P).minChi(2,5)`, it complains
```
ValueError                                Traceback (most recent call last)
<ipython-input-16-5902cbe1f8b3> in <module>
----> 1 gpcca.minChi(2, 5)

~/g-pcca/pyGPCCA/pygpcca/_gpcca.py in minChi(self, m_min, m_max)
    845 
    846         # Calculate Schur matrix R and Schur vector matrix X, if not adequately given.
--> 847         self._do_schur_helper(m_max)
    848         if TYPE_CHECKING:
    849             assert isinstance(self._p_X, np.ndarray)

~/g-pcca/pyGPCCA/pygpcca/_gpcca.py in _do_schur_helper(self, m)
    805                         if _check_conj_split(self._p_eigenvalues[:m]):
    806                             raise ValueError(
--> 807                                 f"Clustering into {m} clusters will split conjugate eigenvalues. "
    808                                 f"Request one cluster more or less."
    809                             )

ValueError: Clustering into 5 clusters will split conjugate eigenvalues. Request one cluster more or less.
```
This is not really nice.
It should rather warn about splitting and still return the values, but not throw an error or not complain at all, since we are just calculating minChi here.

**Comment by msmdev** [comment]
I understand why this happens (since we are using _do_schur helper here as for optimize) but I don't like it - I will think about a fix for this.

**Comment by msmdev** [comment]
> Another suboptimal behaviour:
> If I do `pygpcca.GPCCA(P).minChi(2,11)` it gives me all minChi values (and the aforementioned warning), but if I do `pygpcca.GPCCA(P).minChi(2,5)`, it complains
> 
> ```
> ValueError                                Traceback (most recent call last)
> <ipython-input-16-5902cbe1f8b3> in <module>
> ----> 1 gpcca.minChi(2, 5)
> 
> ~/g-pcca/pyGPCCA/pygpcca/_gpcca.py in minChi(self, m_min, m_max)
>     845 
>     846         # Calculate Schur matrix R and Schur vector matrix X, if not adequately given.
> --> 847         self._do_schur_helper(m_max)
>     848         if TYPE_CHECKING:
>     849             assert isinstance(self._p_X, np.ndarray)
> 
> ~/g-pcca/pyGPCCA/pygpcca/_gpcca.py in _do_schur_helper(self, m)
>     805                         if _check_conj_split(self._p_eigenvalues[:m]):
>     806                             raise ValueError(
> --> 807                                 f"Clustering into {m} clusters will split conjugate eigenvalues. "
>     808                                 f"Request one cluster more or less."
>     809                             )
> 
> ValueError: Clustering into 5 clusters will split conjugate eigenvalues. Request one cluster more or less.
> ```
> 
> This is not really nice.
> It should rather warn about splitting and still return the values, but not throw an error or not complain at all, since we are just calculating minChi here.

Interesting: if I run the tests I get a warning 
```
tests/test_gpcca.py: 10 warnings
  /home/breuter/g-pcca/pyGPCCA/pygpcca/_sort_real_schur.py:106: ComplexWarning: Casting complex values to real discards the imaginary part
    p[k] = R[sk, sk] + np.lib.scimath.sqrt(R[sk + 1, sk] * R[sk, sk + 1])  # store the eigenvalues
``

**Comment by msmdev** [comment]
> I understand why this happens (since we are using _do_schur_helper here as for optimize) but I don't like it - I will think about a fix for this.

I think we have to live with this behavior, since the fix would introduce to many changes and would introduce new issues.

**Comment by msmdev** [comment]
> > Another suboptimal behaviour:
> > If I do `pygpcca.GPCCA(P).minChi(2,11)` it gives me all minChi values (and the aforementioned warning), but if I do `pygpcca.GPCCA(P).minChi(2,5)`, it complains
> > ```
> > ValueError                                Traceback (most recent call last)
> > <ipython-input-16-5902cbe1f8b3> in <module>
> > ----> 1 gpcca.minChi(2, 5)
> > 
> > ~/g-pcca/pyGPCCA/pygpcca/_gpcca.py in minChi(self, m_min, m_max)
> >     845 
> >     846         # Calculate Schur matrix R and Schur vector matrix X, if not adequately given.
> > --> 847         self._do_schur_helper(m_max)
> >     848         if TYPE_CHECKING:
> >     849             assert isinstance(self._p_X, np.ndarray)
> > 
> > ~/g-pcca/pyGPCCA/pygpcca/_gpcca.py in _do_schur_helper(self, m)
> >     805                         if _check_conj_split(self._p_eigenvalues[:m]):
> >     806                             raise ValueError(
> > --> 807                                 f"Clustering into {m} clusters will split conjugate eigenvalues. "
> >     808                                 f"Request one cluster more or less."
> >     809                             )
> > 
> > ValueError: Clustering into 5 clusters will split conjugate eigenvalues. Request one cluster more or less.
> > ```
> > 
> > 
> > This is not really nice.
> > It should rather warn about splitting and still return the values, but not throw an error or not complain at all, since we are just calculating minChi here.
> 
> Interesting: if I run the tests I get a warning
> 
> ```
> tests/test_gpcca.py: 10 warnings
>   /home/breuter/g-pcca/pyGPCCA/pygpcca/_sort_real_schur.py:106: ComplexWarning: Casting complex values to real discards the imaginary part
>     p[k] = R[sk, sk] + np.lib.scimath.sqrt(R[sk + 1, sk] * R[sk, sk + 1])  # store the eigenvalues
> ``
> ```

But I'm still unhappy about this complex warning issue.
@michalk8 @Marius1311 any insights here?

**Comment by msmdev** [comment]
Doing ``tox -e py37-linux-noslepc`` I get in sum the following warnings:
```
============================================ warnings summary ============================================
../../anaconda3/lib/python3.7/importlib/_bootstrap.py:219
../../anaconda3/lib/python3.7/importlib/_bootstrap.py:219
  /home/breuter/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
    return f(*args, **kwds)

pygpcca/utils/_checks.py:11
  /home/breuter/g-pcca/pyGPCCA/pygpcca/utils/_checks.py:11: DeprecationWarning: The get_sectionsf method is deprecated, use the get_sections method instead. get_sectionsf will be removed in 0.4.0
    @d.get_sectionsf("assert_array", sections=["Parameters"])

tests/test_gpcca.py: 10 warnings
  /home/breuter/g-pcca/pyGPCCA/pygpcca/_sort_real_schur.py:106: ComplexWarning: Casting complex values to real discards the imaginary part
    p[k] = R[sk, sk] + np.lib.scimath.sqrt(R[sk + 1, sk] * R[sk, sk + 1])  # store the eigenvalues

-- Docs: https://docs.pytest.org/en/stable/warnings.html
```

**Comment by msmdev** [comment]
Ok, taking a look on the CI results online, the ComplexWarning appears as well.
So you wouldn't worry about this?

**Comment by michalk8** [comment]
> Ok, taking a look on the CI results online, the ComplexWarning appears as well.
So you wouldn't worry about this?

Let me check - I know that `np.libscimath.sqrt` return a comlex, which most likely means `p` is not complex and the imaginary part gets truncated. If `p` shouldn't be complex, I will silence the warning, but it should, we should change it's dtype (might be also R's dtype, but it shouldn't be).

**Comment by michalk8** [comment]
@msmdev 
Could you please enable on `readthedocs.io` to build documentation in PRs - that means we can all see the newest version here: 
https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html

**Comment by msmdev** [comment]
> @msmdev
> Could you please enable on `readthedocs.io` to build documentation in PRs - that means we can all see the newest version here:
> https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html

Done!

**Comment by michalk8** [comment]
@msmdev 
I've changed the dtype to complex64 (I remember previously, it was a Python list, so it wasn't a problem), locally tests pass.
Also fixed the warning in `pygpcca/utils/_checks.py:11`. Thanks for catching both of these. I wonder whether it not being complex caused all those macOS/mu=0 issues (I will test for this in a separate PR).

**Comment by msmdev** [comment]
> > @msmdev
> > Could you please enable on `readthedocs.io` to build documentation in PRs - that means we can all see the newest version here:
> > https://docs.readthedocs.io/en/stable/guides/autobuild-docs-for-pull-requests.html
> 
> Done!

Could it be that I also have to activate the example-notebook version under "versions" on readthedocs.org?

**Comment by msmdev** [comment]
> @msmdev
> I've changed the dtype to complex64 (I remember previously, it was a Python list, so it wasn't a problem), locally tests pass.
> Also fixed the warning in `pygpcca/utils/_checks.py:11`. Thanks for catching both of these. I wonder whether it not being complex caused all those macOS/mu=0 issues (I will test for this in a separate PR).

I see - I remember you changed from list to vector at some point for some reason.
Thx, for solving this!

**Comment by michalk8** [comment]
@msmdev could you review please quickly review this PR? From my side, everything is ready (I've checked the links + added a spell-checker, only 2 typos I think).

**Comment by msmdev** [comment]
@michalk8 sure!
So no need to activate the example-notebook version under "versions" on readthedocs.org, since we will merge this soon.

**Comment by msmdev** [comment]
> I added an extra copyright note to the function docstrings in _utils.py - just in case.
> @michalk8 the functions _sds and _sdd don't have docstrings currently - do they also origin from msmtools?

@michalk8 do you remember, if _sds and _sdd in _utils.py also originate from msmtools?

**Comment by msmdev** [comment]
@Marius1311 do you have input on the contribution section you wanted to add to index.rst to credit Michal and you?

**Comment by michalk8** [comment]
> @michalk8 do you remember, if _sds and _sdd in _utils.py also originate from msmtools?

They do: https://github.com/msmdev/msmtools/blob/devel/msmtools/analysis/sparse/stationary_vector.py#L2

**Comment by msmdev** [comment]
> > @michalk8 do you remember, if _sds and _sdd in _utils.py also originate from msmtools?
> 
> They do: https://github.com/msmdev/msmtools/blob/devel/msmtools/analysis/sparse/stationary_vector.py#L2

Indeed, but you made some functional improvements as far as I can see.
So mb. the Copyright note
```
Copyright
 ---------
This function origins from MSMTools
Copyright (c) 2015, 2014 Computational Molecular Biology Group
Freie Universitaet Berlin (GER)
```
in the docstrings and the header

# The code of the functions below was taken from MSMTools.
#
# Copyright (c) 2015, 2014 Computational Molecular Biology Group, Freie Universitaet Berlin (GER)

is not really precise and we would need to clarify that changes were made...

**Comment by Marius1311** [comment]
> @Marius1311 do you have input on the contribution section you wanted to add to index.rst to credit Michal and you?

Yes! I was thinking of something along the lines of scanpy's "Key contributors" box, see https://scanpy.readthedocs.io/en/latest/
What's your opinion?

**Comment by msmdev** [comment]
> > @Marius1311 do you have input on the contribution section you wanted to add to index.rst to credit Michal and you?
> 
> Yes! I was thinking of something along the lines of scanpy's "Key contributors" box, see https://scanpy.readthedocs.io/en/latest/
> What's your opinion? I think it's a nice way to credit us and also potential future key contributors.

@Marius1311 looks fine - could you provide this or should I set it up?

**Comment by Marius1311** [comment]
> > > @Marius1311 do you have input on the contribution section you wanted to add to index.rst to credit Michal and you?
> > 
> > 
> > Yes! I was thinking of something along the lines of scanpy's "Key contributors" box, see https://scanpy.readthedocs.io/en/latest/
> > What's your opinion? I think it's a nice way to credit us and also potential future key contributors.
> 
> @Marius1311 looks fine - could you provide this or should I set it up?

Would be great if you could set this up, I'm pretty occupied with revision work atm. If you push a draft, I'm happy to give feedback and suggest potential changes if at all needed.

**Comment by msmdev** [comment]
> > > > @Marius1311 do you have input on the contribution section you wanted to add to index.rst to credit Michal and you?
> > > 
> > > 
> > > Yes! I was thinking of something along the lines of scanpy's "Key contributors" box, see https://scanpy.readthedocs.io/en/latest/
> > > What's your opinion? I think it's a nice way to credit us and also potential future key contributors.
> > 
> > 
> > @Marius1311 looks fine - could you provide this or should I set it up?
> 
> Would be great if you could set this up, I'm pretty occupied with revision work atm. If you push a draft, I'm happy to give feedback and suggest potential changes if at all needed.

@Marius1311 I made a first draft [5ecee38](https://github.com/msmdev/pyGPCCA/pull/12/commits/5ecee3851328160a467e1858333475275a059639) check it out!

**Comment by michalk8** [comment]
I'm really happy with this from my side, I think we can merge.

**Comment by Marius1311** [comment]
I'm happy as well, feel free to merge this!

**Comment by michalk8** [comment]
Seems everyone is happy, merging this!

**Pull request merged**
